### ISSUE TITLE
Dump of co-pilot reporting data

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/job-server#3790]
@acagreen17 asked for a dump of the co-pilot reporting data.[^1] This feels like a playbook entry that hasn't been written. I followed the instructions in the "[Dumping co-pilot reporting data](https://github.com/opensafely-core/job-server/blob/main/DEVELOPERS.md#dumping-co-pilot-reporting-data)" section of `DEVELOPERS.md`, but encountered the following error:

```
<snip>
  jobserver_releasefile.workspace_id => jobserver_workspace.id
Traceback (most recent call last):
  File "/Users/iaindillingham/.local/bin/db-to-sqlite", line 8, in <module>
    sys.exit(cli())
  File "/Users/iaindillingham/.local/pipx/venvs/db-to-sqlite/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/iaindillingham/.local/pipx/venvs/db-to-sqlite/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/iaindillingham/.local/pipx/venvs/db-to-sqlite/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/iaindillingham/.local/pipx/venvs/db-to-sqlite/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/iaindillingham/.local/pipx/venvs/db-to-sqlite/lib/python3.10/site-packages/db_to_sqlite/cli.py", line 166, in cli
    db.add_foreign_keys(foreign_keys_to_add_final)
  File "/Users/iaindillingham/.local/pipx/venvs/db-to-sqlite/lib/python3.10/site-packages/sqlite_utils/db.py", line 1143, in add_foreign_keys
    cursor.execute(
sqlite3.OperationalError: table sqlite_master may not be modified
```

[^1]: https://bennettoxford.slack.com/archives/C028EJH752A/p1699627796998339

**Comment by benbc** [comment]
Pipeline team: if you want tech support to be able to handle this, can you figure out the problem that Iain ran into _and_ add an entry to [the playbook](https://bennettinstitute-team-manual.pages.dev/tech-group/tech-support/playbook/)?

**Comment by iaindillingham** [comment]
@ghickman, you asked[^1] whether I had a pre-existing `jobserver.sqlite` when the command failed. I didn't 🙁 

[^1]: https://bennettoxford.slack.com/archives/C028EJH752A/p1700238736333109?thread_ts=1699627796.998339&cid=C028EJH752A

**Comment by benbc** [comment]
@lucyb Would you consider Millie's suggestion as part deck scrubbing/George handover?

**Comment by bloodearnest** [comment]
FTR, I originally wrote this tooling, so I know how to do it.

**Comment by benbc** [comment]
Oh, fine. I take back my request.
